In [1]:
print('upiter')

upiter

In [2]:
print(1+2)

3

In [3]:
import os
print(os.getcwd())

C:\Users\onyan\anaconda_projects

In [4]:
import pandas as pd
df = pd.read_csv("customers.csv")
df

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,EB54EF1154C3A78,Heather,Callahan,Mosley-David,Lake Jeffborough,Norway,043-797-5229,915.112.1727,urangel@espinoza-francis.net,2020-08-26,http://www.escobar.org/
1,2,10dAcafEBbA5FcA,Kristina,Ferrell,"Horn, Shepard and Watson",Aaronville,Andorra,932-062-1802,(209)172-7124x3651,xreese@hall-donovan.com,2020-04-27,https://tyler-pugh.info/
2,3,67DAB15Ebe4BE4a,Briana,Andersen,Irwin-Oneal,East Jordan,Nepal,8352752061,(567)135-1918,haleybraun@blevins-sexton.com,2022-03-22,https://www.mack-bell.net/
3,4,6d350C5E5eDB4EE,Patty,Ponce,Richardson Group,East Kristintown,Northern Mariana Islands,302.398.3833,196-189-7767x770,hohailey@anthony.com,2020-07-02,https://delacruz-freeman.org/
4,5,5820deAdCF23EFe,Kathleen,Mccormick,Carson-Burch,Andresmouth,Macao,001-184-153-9683x1497,552.051.2979x342,alvaradojesse@rangel-shields.com,2021-01-17,https://welch.info/
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,DD0caa06ebf217c,Meghan,Cline,Richardson LLC,Petersport,Cote d'Ivoire,001-270-136-4738x419,001-349-692-1755x055,nicolasandrade@bates.info,2022-04-27,http://thomas-ramos.com/
9996,9997,C1C62ff90D0AfED,Jeremiah,Pena,Hodge-Nixon,Briggsport,Namibia,+1-531-494-7645x4844,001-295-324-5502x5411,tracy68@wade.com,2022-01-17,https://www.campbell.com/
9997,9998,2EfAa6Fe435A7DA,Peggy,Key,Vang LLC,West Joyceport,United States Virgin Islands,520.109.2482x26052,+1-602-934-5901x95106,mclaughlinjulia@barnett-dorsey.com,2022-01-13,http://www.george-scott.com/
9998,9999,5dB06C3Fab5CCCb,Evan,Humphrey,Gould Ltd,Camachochester,Niger,001-465-242-9979,001-639-955-2116x751,velazquezjessica@villegas-wilcox.com,2020-04-14,https://www.payne.info/
9999,10000,9903e8fF4D8Ff0F,Melissa,Montgomery,Burns-Holden,Sparkstown,Tunisia,+1-889-682-9490x65400,423.632.2539x98740,ngallagher@martinez.com,2020-06-27,http://nixon.net/

In [5]:
df.shape

(10000, 12)

In [6]:
df.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,EB54EF1154C3A78,Heather,Callahan,Mosley-David,Lake Jeffborough,Norway,043-797-5229,915.112.1727,urangel@espinoza-francis.net,2020-08-26,http://www.escobar.org/
1,2,10dAcafEBbA5FcA,Kristina,Ferrell,"Horn, Shepard and Watson",Aaronville,Andorra,932-062-1802,(209)172-7124x3651,xreese@hall-donovan.com,2020-04-27,https://tyler-pugh.info/
2,3,67DAB15Ebe4BE4a,Briana,Andersen,Irwin-Oneal,East Jordan,Nepal,8352752061,(567)135-1918,haleybraun@blevins-sexton.com,2022-03-22,https://www.mack-bell.net/
3,4,6d350C5E5eDB4EE,Patty,Ponce,Richardson Group,East Kristintown,Northern Mariana Islands,302.398.3833,196-189-7767x770,hohailey@anthony.com,2020-07-02,https://delacruz-freeman.org/
4,5,5820deAdCF23EFe,Kathleen,Mccormick,Carson-Burch,Andresmouth,Macao,001-184-153-9683x1497,552.051.2979x342,alvaradojesse@rangel-shields.com,2021-01-17,https://welch.info/

In [7]:
df.head().shape()

TypeError: 'tuple' object is not callable

In [8]:
df.columns

Index(['Index', 'Customer Id', 'First Name', 'Last Name', 'Company', 'City',
       'Country', 'Phone 1', 'Phone 2', 'Email', 'Subscription Date',
       'Website'],
      dtype='str')

In [11]:
df.City[200:210]

200        Dillonborough
201        Castanedaview
202          Port Marisa
203            Wandastad
204             East Jim
205         West Brendan
206       New Waynemouth
207         Lake Timothy
208         New Chadport
209    North Andreamouth
Name: City, dtype: str

In [12]:
type(df['Country'])

pandas.Series

In [14]:
df.describe()

             Index
count  10000.00000
mean    5000.50000
std     2886.89568
min        1.00000
25%     2500.75000
50%     5000.50000
75%     7500.25000
max    10000.00000

In [18]:
df[df.Country=="Kenya"]

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
436,437,D40eba5Dc71C4E5,Daniel,Carrillo,"Leon, Lang and Reilly",Pittsport,Kenya,6907120293,(777)479-0991x9736,parkerlogan@sutton-wheeler.com,2021-12-03,http://www.johns-lutz.org/
1331,1332,f57eDD9101aD737,Mikayla,Lutz,Herman Ltd,Vickieside,Kenya,001-256-524-7975x8997,467.801.8833x67445,ocombs@peck.com,2020-11-11,http://www.higgins.com/
1428,1429,a8fB2E2D94B0720,Candice,Heath,"Pratt, Gentry and Crane",Marilynside,Kenya,+1-995-903-8844x949,001-404-730-6018x77942,probertson@stokes.com,2021-07-05,http://www.middleton-floyd.com/
1471,1472,32eFD1dCaF2980e,Ann,Garner,Stout Ltd,Sharpport,Kenya,619-528-9084x4155,+1-269-846-4158x1039,chungnancy@hoover.biz,2021-07-24,https://www.mccarthy.com/
1846,1847,d4B5b7f4f19A1a2,Edgar,Bernard,Gay-Benitez,Port Yvonne,Kenya,(861)254-0855x515,456.382.5387,amack@cordova.info,2022-03-06,https://burgess.com/
2366,2367,afe3Dd2df8dBc9d,Andrea,Gilmore,Melton Group,Feliciastad,Kenya,211-754-7827x4048,269-513-6213x43976,tkelly@chaney-decker.org,2020-12-05,https://www.mills.com/
2663,2664,5Bfef99aA5ba004,Logan,Douglas,Oneill-Frey,Hannahmouth,Kenya,3428030633,654-515-9205x4181,wernertravis@dickson-wells.com,2021-12-12,http://morris.com/
3250,3251,bcEaA988648d3E3,Traci,May,Harris-Anthony,New Frankton,Kenya,986-340-0253,+1-061-966-9225x64166,alexandra21@kemp.biz,2020-05-24,https://www.dudley.com/
3359,3360,AAe7ab9dc73Ea1c,Mia,Compton,"Patterson, Frazier and Wilkinson",Cindytown,Kenya,9998282143,993.394.6951,hoodvalerie@everett.com,2021-11-12,https://www.knox.com/
3407,3408,dC9dc0BB8f757E1,Victor,Case,Maxwell-Sloan,Lake Vanessa,Kenya,249.180.2602x400,831.283.5049x838,barbaramoore@elliott.org,2020-11-19,https://mccoy.info/
3419,3420,5E232F407AA85eF,Kirk,Ray,Bates-Johnson,Lake Ronnie,Kenya,(466)371-1645x28115,2897918399,gibbsphilip@wilkerson.net,2022-05-02,http://house.info/
4027,4028,60aa9c3C25D8cef,Andres,Mayer,"Case, Bradford and Giles",Port Veronica,Kenya,+1-733-805-3414,+1-817-150-0168x7473,obrady@noble-curtis.com,2020-03-20,http://mcgrath.com/
4051,4052,4e1fcAbF5bFC0ac,Jared,Mckinney,"Gallegos, Munoz and Rivas",Port Kendraville,Kenya,001-976-663-3920,137.700.3011x128,logantaylor@villa.org,2021-01-01,https://www.moss.com/
4168,4169,5bFeE01a9b4ff84,Judith,Tate,"Hooper, Wu and Ramos",Woodsshire,Kenya,022-290-9533,(938)916-6950x3633,sheryldiaz@thomas-fisher.com,2021-12-08,http://boone.net/
4639,4640,7D6fCe1Dbfa27D3,Catherine,Sparks,Wheeler-Meadows,Chaseton,Kenya,(081)175-8296,102.140.8213x54530,ymorrow@huang.com,2020-01-26,https://parker.biz/
4691,4692,AD41eD85a3829F8,Julie,Hutchinson,Bird Inc,Gilbertport,Kenya,(323)997-1348x9961,3732749710,joelgreer@neal-fitzgerald.com,2021-08-26,http://www.frederick.com/
5142,5143,CF00A8415C9c9FA,Tim,Lowe,"Howell, Faulkner and Malone",Patrickville,Kenya,775-944-1786x4549,9619857515,nsilva@frazier.com,2020-08-30,http://www.fischer.com/
5347,5348,CA35Ba6BDE3ef18,Ashlee,Giles,"Lin, Barrera and Ortega",North Garrett,Kenya,234-165-0180x95290,+1-219-914-9872x10004,uvelazquez@pratt.biz,2020-05-03,https://www.moon-bolton.org/
5570,5571,b5C0eCab93ff0Be,Gina,Hines,Burton PLC,Alejandroland,Kenya,655.231.9348,(369)605-6772,nmccormick@mcclure.net,2022-03-27,https://odonnell-cherry.net/
5695,5696,ebaAa48B8e9F6Eb,Jesus,Juarez,Blanchard Inc,Port Christina,Kenya,001-292-275-0778x5391,(398)760-6403x088,briggsnichole@alvarado.net,2021-05-22,https://www.ferrell.org/
5938,5939,8F8CaD61FECcB19,Lacey,Welch,"Bruce, Hart and Bautista",Alejandrofort,Kenya,(135)475-9034x9214,198-416-8413x57135,teresacharles@ewing.org,2022-05-03,http://www.mosley.com/
6096,6097,e9BB57b71Eb743a,Danny,Rodriguez,Reyes Inc,New Warrenland,Kenya,(387)223-3969x4662,705.627.1880,randallstefanie@reyes.info,2022-02-05,http://quinn.net/
6295,6296,1DA67cc7379B24d,Linda,Jones,Reid and Sons,Lake Reginaldton,Kenya,001-140-360-1618x1370,7113488786,joycepreston@black-warner.com,2021-08-14,http://valencia-horton.biz/
6372,6373,c00B7286C0Ee99d,Andrew,Richards,Shea-Bush,Davidtown,Kenya,(803)074-2374x9631,001-441-257-0884,garrett61@gonzalez-welch.com,2020-03-09,https://www.schmitt.net/
7526,7527,F090dcEF5D96CF9,Andre,Ellison,Savage and Sons,Port Evanstad,Kenya,+1-636-914-8921,+1-519-081-6405x3006,yhuffman@dunn.com,2020-05-21,https://russo-cook.com/
7578,7579,CD752A01Dc8428B,Kellie,Carr,Pitts Ltd,South Erinberg,Kenya,001-060-302-4416x6526,001-154-369-6052x36817,nina32@atkins.com,2020-10-06,https://ponce-ochoa.net/
8131,8132,72EC0E37eb53cb2,Kristin,Crosby,Ray-Newman,Bettyside,Kenya,001-508-104-0224x2123,001-450-651-3857x23568,alisonpotts@lamb.com,2020-11-24,http://www.parsons.com/
8223,8224,d6F5Cd2D7EDa18C,Tim,Blevins,"Floyd, Barrett and Moreno",South Joanbury,Kenya,(290)087-1979,+1-736-277-8208,vicki91@underwood.com,2021-04-26,http://mcmahon-travis.info/
8235,8236,3cbFaec1C8e7a3b,Stacey,Nguyen,"Velazquez, Knapp and Lam",West Faith,Kenya,227.343.7799x557,+1-219-402-9180x5231,pwheeler@holland.net,2021-07-21,https://blackburn.biz/
8240,8241,1BC4a00171e11De,Brittany,Singleton,Edwards-Little,West Lynnland,Kenya,811.234.0707,+1-597-097-3103x8081,dbray@richards.org,2022-01-06,https://pittman-newman.com/
8309,8310,7BBd1805E1FE540,Roy,Frank,Donaldson LLC,Pecktown,Kenya,001-037-296-8897,451-385-0745,leonhendricks@garner-little.biz,2021-10-21,http://dickerson.com/
9055,9056,6dfe9E67F5eFAbb,Deanna,Tapia,Torres-Hampton,North Bethtown,Kenya,001-428-928-4516x11954,(882)117-0078,derekmayo@randall.com,2021-07-07,http://hall.com/
9137,9138,84e2381cDDB5CD7,Ryan,Weeks,Tanner-Mcintosh,South Joshuachester,Kenya,632.337.0482x287,(957)742-1493x3057,vrichards@mclaughlin.net,2020-11-25,https://www.compton.com/
9305,9306,F24Eb26bFAE93E1,Earl,Hebert,"Hester, Mcdaniel and Wiley",South Katie,Kenya,001-719-999-6391,001-894-633-3827,deborahgentry@mayo-bolton.org,2021-12-25,https://www.hawkins-goodwin.com/
9429,9430,A4c3f8CF4aD3A99,Jaime,Powell,Stark-Lucas,Marisaview,Kenya,001-608-418-8616x5028,001-269-511-2001,merceryvonne@riddle.biz,2021-09-16,http://rush.net/
9799,9800,6367daE04d83CBd,Anna,Christian,Joseph and Sons,East Janice,Kenya,930-719-7660x35676,911-189-2672,marcodunn@chapman.com,2020-12-17,http://www.kirby-lowe.org/
9818,9819,61cFB7af9728b8e,Sara,Armstrong,Dennis-Wang,East Katelynmouth,Kenya,(172)442-9477,(663)085-1437,eugene05@foster.com,2020-10-28,http://www.cordova.org/

import pandas as pd
df = pd.read_csv('weather.csv)
df